config/routes.rb
Rails.application.routes.draw do
  get 'login/index'
  get '/download/:id', to: 'leave_applications#download', as: 'download'
  devise_for :users

  resources :leave_types
  resources :leave_applications
  put "leave_applications/:id/review", to: "leave_applications#review", as: "review"
  resources :approvals
  resources :users

  root 'leave_applications#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leave_application.rb
class LeaveApplication < ApplicationRecord
  belongs_to :user
  belongs_to :leave_type

  mount_uploader :attachment, AvatarUploader

  validates :leave_type, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :leave_duration, presence: true
  validates :reason, presence: true
  validate :valid_date
  validate :valid_length

  enum leave_duration: [ :full_day, :am, :pm ]
  enum status: [ :pending, :approved, :rejected ]

  def valid_length
    duration = start_date.business_days_until(end_date) + 1
    count = user.records.find_by_leave_type_id(leave_type).days

    if duration > count
      errors.add(:remaining_leave_days, " insufficient")
    end
  end

  def valid_date
    if start_date > end_date
      errors.add(:start_date, " cannot be after end date")
    end
  end

  def start_time
    self.start_date
  end

  def end_time
    self.end_date
  end

  def title
    user.name
  end
end

app/models/leave_type.rb
class LeaveType < ApplicationRecord
  has_many :records
  has_many :users, through: :records

  validates :name, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :leave_type
  accepts_nested_attributes_for :leave_type, allow_destroy: true,
                                reject_if: proc { |attributes| attributes.all? { |key, value| key == "_destroy" || value.blank? }}
end

app/models/user.rb
require 'role_model'

class User < ApplicationRecord
  has_many :leave_applications
  has_many :records, dependent: :destroy
  has_many :leave_types, through: :records
  accepts_nested_attributes_for :records, allow_destroy: true

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :region, presence: true

  include RoleModel
  roles_attribute :roles_mask
  roles :employee, :head, :director, :admin

  enum department: [ :Tech, :Creative, :Sales, :Procurement, :Logistics, :People, :Finance ]
  enum region: [ :Malaysia, :Singapore ]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  def index
    @q = LeaveApplication.ransack(params[:q])

    if current_user.is_any_of? :director, :admin 
      @leave_applications = @q.result.includes(:user)
    else
      ids = User.where(department: current_user.department).ids
      @leave_applications = @q.result.where(user_id: ids, status: 0).includes(:user)
    end
  end
end

app/controllers/leave_applications_controller.rb
require 'open-uri'
class LeaveApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_filter :set_beginning_of_week

  def download
    @leave_application = LeaveApplication.find(params[:id])
    url = @leave_application.attachment.file.to_file
    data = open(url).read
    send_data url, type: "image/jpeg", disposition: "attachment"
  end

  def index
    @q = LeaveApplication.ransack(params[:q])
    @leaves = LeaveApplication.where(status: 1)

    ids = User.where(department: current_user.department).ids
    @leave_applications = @q.result.where(user_id: ids)
  end

  def show
    @leave_application = LeaveApplication.find(params[:id])
  end

  def new
    @leaves = LeaveApplication.where(status: 1)
    @leave_application = LeaveApplication.new
  end

  def edit
    @leaves = LeaveApplication.where(status: 1)
    @leave_application = LeaveApplication.find(params[:id])
  end

  def create
    @leave_application = current_user.leave_applications.new(leave_application_params)

    if @leave_application.save
      redirect_to @leave_application
    else
      @leaves = LeaveApplication.where(status: 1)
      render :new
    end
  end

  def update
    @leave_application = LeaveApplication.find(params[:id])

    if @leave_application.update(leave_application_params)
      @leave_application.save
      redirect_to @leave_application
    else
      render :edit
    end
  end

  def review
    @leave_application = LeaveApplication.find(params[:id])
    @leave_application.update_attribute(:status, params[:status].to_i)

    if @leave_application.approved?
      duration = @leave_application.start_date.business_days_until(@leave_application.end_date) + 1
      type = @leave_application.leave_type_id
      @record = @leave_application.user.records.find_by_leave_type_id(type)
      @record.days -= duration
      @record.save
    end

    redirect_to approvals_path
  end

  def destroy
    @leave_application = LeaveApplication.find(params[:id])
    @leave_application.destroy

    if @leave_application.approved?
      duration = @leave_application.start_date.business_days_until(@leave_application.end_date) + 1
      type = @leave_application.leave_type_id
      @record = @leave_application.user.records.find_by_leave_type_id(type)
      @record.days += duration
      @record.save
    end

    redirect_back(fallback_location: root_path)
  end

  private
    def leave_application_params
      params.require(:leave_application).permit(:leave_type_id, :start_date, :end_date, :leave_duration, :reason, :attachment, :status)
    end

    def set_beginning_of_week
      Date.beginning_of_week = :sunday
    end
end

app/controllers/leave_types_controller.rb
class LeaveTypesController < ApplicationController
  def show
    @leave_type = LeaveType.find(params[:id])
  end

  def new
    @leave_type = LeaveType.new
  end

  def create
    @leave_type = LeaveType.new(leave_type_params)

    if @leave_type.save
      redirect_to @leave_type
    else
      render 'new'
    end
  end

  private
    def leave_type_params
      params.require(:leave_type).permit(:name)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @q = User.ransack(params[:q])

    if current_user.is_any_of? :director, :admin
      @users = @q.result.includes(:records).uniq
    else
      @users = @q.result.where(department: current_user.department).includes(:records).uniq
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :department, :region, :email, :password, roles: [], records_attributes: [:id, :days, :leave_type_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/helpers/leave_applications_helper.rb
module LeaveApplicationsHelper
end

app/helpers/leave_types_helper.rb
module LeaveTypesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/approvals/index.html.erb
<div class="row">
  <%= search_form_for @q, url: approvals_path do |f| %>
    <div class="large-3 large-offset-1 columns">
      <%= f.label :start_date_start %>
      <%= f.search_field :start_date_start %>
    </div>
    <div class="large-3 columns">
      <%= f.label :end_date_start %>
      <%= f.search_field :end_date_start %>
    </div>
    <div class="large-3 columns">
      <%= f.label :user_name_cont %>
      <%= f.search_field :user_name_cont %>
    </div>
    <br>
    <div class="large-1 columns">
      <%= f.button :Search, class: "button" %>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="large-12 columns">
    <table>
      <thead>
        <tr>
          <th><%= sort_link(@q, :created_at, 'Submitted On') %></th>
          <th><%= sort_link(@q, :user_name, 'Name') %></th>
          <% if current_user.is_any_of? :director, :admin %>
            <th><%= sort_link(@q, :user_department, 'Department') %></th>
          <% end %>
          <th><%= sort_link(@q, :leave_type, 'Leave Type') %></th>
          <th><%= sort_link(@q, :start_date, 'Start Date') %></th>
          <th><%= sort_link(@q, :end_date, 'End Date') %></th>
          <th><%= sort_link(@q, :leave_duration, 'Leave Duration') %></th>
          <th><%= sort_link(@q, :reason, 'Reason') %></th>
          <th><%= sort_link(@q, :attachment, 'Attachment') %></th>
          <th><%= sort_link(@q, :status, 'Status') %></th>
        </tr>
      </thead>

      <tbody>
        <% @leave_applications.each do |leave_application| %>
          <% if (leave_application.user.id != current_user.id) && leave_application.pending? %>
            <tr>
              <td><%= leave_application.created_at.strftime('%d/%m') %></td>
              <td><%= leave_application.user.name %></td>
              <% if current_user.is_any_of? :director, :admin %>
                <td><%= leave_application.user.department %></td>
              <% end %>
              <td><%= leave_application.leave_type.name %></td>
              <td><%= leave_application.start_date.strftime('%d/%m') %></td>
              <td><%= leave_application.end_date.strftime('%d/%m') %></td>
              <td><%= leave_application.leave_duration %></td>
              <td><%= leave_application.reason %></td>
              <td><%= link_to 'Download', download_path(leave_application.id) if leave_application.attachment.present? %></td>
              <td><%= leave_application.status %></td>
              <td>
                <%= button_to 'Approve', review_path(leave_application), method: :put, params: { status: LeaveApplication.statuses[:approved] }, data: { confirm: 'Are you sure?' }, class: "success button"%>
              </td>
              <td>
                <%= button_to 'Reject', review_path(leave_application), method: :put, params: { status: LeaveApplication.statuses[:rejected] }, data: { confirm: 'Are you sure?' }, class: "alert button" %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="large-12 columns">
    <table>
      <caption>Approved Leave Applications</caption>
      <thead>
        <tr>
          <th><%= sort_link(@q, :created_at, 'Submitted On') %></th>
          <th><%= sort_link(@q, :user_name, 'Name') %></th>
          <% if current_user.is_any_of? :director, :admin %>
            <th><%= sort_link(@q, :user_department, 'Department') %></th>
          <% end %>
          <th><%= sort_link(@q, :leave_type, 'Leave Type') %></th>
          <th><%= sort_link(@q, :start_date, 'Start Date') %></th>
          <th><%= sort_link(@q, :end_date, 'End Date') %></th>
          <th><%= sort_link(@q, :leave_duration, 'Leave Duration') %></th>
          <th><%= sort_link(@q, :reason, 'Reason') %></th>
          <th><%= sort_link(@q, :attachment, 'Attachment') %></th>
        </tr>
      </thead>

      <tbody>
        <% @leave_applications.each do |leave_application| %>
          <% if leave_application.user.id != current_user.id && leave_application.approved? %>
            <tr>
              <td><%= leave_application.created_at.strftime('%d/%m') %></td>
              <td><%= leave_application.user.name %></td>
              <% if current_user.is_any_of? :director, :admin %>
                <td><%= leave_application.user.department %></td>
              <% end %>
              <td><%= leave_application.leave_type.name %></td>
              <td><%= leave_application.start_date.strftime('%d/%m') %></td>
              <td><%= leave_application.end_date.strftime('%d/%m') %></td>
              <td><%= leave_application.leave_duration %></td>
              <td><%= leave_application.reason %></td>
              <td><%= link_to 'Download', download_path(leave_application.id) if leave_application.attachment.present? %></td>
              <td><%= link_to 'Destroy', leave_application_path(leave_application), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="large-12 columns">
    <table>
      <caption>Rejected Leave Applications</caption>
      <thead>
        <tr>
          <th><%= sort_link(@q, :created_at, 'Submitted On') %></th>
          <th><%= sort_link(@q, :user_name, 'Name') %></th>
          <% if current_user.is_any_of? :director, :admin %>
            <th><%= sort_link(@q, :user_department, 'Department') %></th>
          <% end %>
          <th><%= sort_link(@q, :leave_type, 'Leave Type') %></th>
          <th><%= sort_link(@q, :start_date, 'Start Date') %></th>
          <th><%= sort_link(@q, :end_date, 'End Date') %></th>
          <th><%= sort_link(@q, :leave_duration, 'Leave Duration') %></th>
          <th><%= sort_link(@q, :reason, 'Reason') %></th>
          <th><%= sort_link(@q, :attachment, 'Attachment') %></th>
        </tr>
      </thead>

      <tbody>
        <% @leave_applications.each do |leave_application| %>
          <% if leave_application.user.id != current_user.id && leave_application.rejected? %>
            <tr>
              <td><%= leave_application.created_at.strftime('%d/%m') %></td>
              <td><%= leave_application.user.name %></td>
              <% if current_user.is_any_of? :director, :admin %>
                <td><%= leave_application.user.department %></td>
              <% end %>
              <td><%= leave_application.leave_type.name %></td>
              <td><%= leave_application.start_date.strftime('%d/%m') %></td>
              <td><%= leave_application.end_date.strftime('%d/%m') %></td>
              <td><%= leave_application.leave_duration %></td>
              <td><%= leave_application.reason %></td>
              <td><%= link_to 'Download', download_path(leave_application.id) if leave_application.attachment.present? %></td>
              <td><%= link_to 'Destroy', leave_application_path(leave_application), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <div class="top-bar">
        <div class="top-bar-left">
          <ul class="menu">
            <li class="menu-text">Saltyleave</li>
            <li class="menu-text"><%= user_signed_in? ? "Current User: #{current_user.name}" : 'Log In' %></li>
          </ul>
        </div>

        <% if user_signed_in? %>
          <div class="top-bar-right">
            <ul class="menu">
              <li><a href="/leave_applications">View Leave Applications</a></li>
              <li><a href="/leave_applications/new">Apply for Leave</a></li>
              <% if current_user.is_any_of? :head, :director, :admin %>
                <li><a href="/approvals">Approve Leave Applications</a></li>
                <li><a href="/users">View Users</a></li>
                <li><a href="/leave_types/new">Add Leave Type</a></li>
              <% end %>
              <li><a href="/users/sign_out" data-method="delete" class="alert button">Log Out</a></li>
            </ul>
          </div>
        <% end %>
      </div>
    </header>
    <br>

    <%= yield %>
  </body>
</html>

app/views/leave_applications/_form.html.erb
<div class="row">
  <div class="large-7 columns">
    <div id="calendar"></div>
  </div>

  <div class="large-4 large-offset-1 columns">
    <% if @leave_application.errors.any? %>
      <div class="callout alert" id="error_explanation">
        <h4>
          <%= pluralize(@leave_application.errors.count, "error") %> prohibited this application from being saved:
        </h4>
        <ul>
          <% @leave_application.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="callout">
      <% current_user.records.each do |r| %>
        <h6>
          <strong><%= "#{pluralize(r.days, 'day')}" %></strong>
          <%= " of #{r.leave_type.name.downcase} leave available" %>
        </h6>
      <% end %>
    </div>

    <%= simple_form_for @leave_application do |f| %>
      <%= f.input :leave_type_id, collection: current_user.records.collect{|r| ["#{r.leave_type.name}", r.leave_type_id]}, include_blank: false %>
      <%= f.input :start_date, as: :date %>
      <%= f.input :end_date, as: :date %>
      <%= f.input :leave_duration, collection: LeaveApplication.leave_durations.keys, include_blank: false %>
      <%= f.input :reason, as: :text, placeholder: 'Enter a brief description', error: false %>
      <%= f.input :attachment, as: :file, required: false %>
      <%= f.button :submit, "Submit Leave Application", class: "button" %>
    <% end %>
  </div>
</div>

app/views/leave_applications/edit.html.erb
<%= render "form" %>

app/views/leave_applications/index.html.erb
<div class="row">
  <div class="columns">
    <ul class="tabs" data-tabs id="index-tabs">
      <li class="tabs-title is-active"><a href="#leave_calendar">Calendar</a></li>
      <li class="tabs-title"><a href="#tables">Leave Applications</a></li>
    </ul>

    <div class="tabs-content" data-tabs-content="index-tabs">
      <div class="tabs-panel is-active" id="leave_calendar">
        <div id="calendar"></div>
      </div>
      <div class="tabs-panel" id="tables">
        <table>
          <caption>Your Leave Applications</caption>
          <thead>
            <tr>
              <th>Date</th>
              <th>Leave Type</th>
              <th>Start Date</th>
              <th>End Date</th>
              <th>Leave Duration</th>
              <th>Reason</th>
              <th>Status</th>
            </tr>
          </thead>

          <tbody>
            <% @leave_applications.each do |leave_application| %>
              <% if leave_application.user_id == current_user.id %>
                <tr>
                  <td><%= leave_application.created_at.strftime('%d/%m') %></td>
                  <td><%= leave_application.leave_type.name %></td>
                  <td><%= leave_application.start_date.strftime('%d/%m') %></td>
                  <td><%= leave_application.end_date.strftime('%d/%m') %></td>
                  <td><%= leave_application.leave_duration %></td>
                  <td><%= leave_application.reason %></td>
                  <td><%= leave_application.status %></td>
                  <% if leave_application.status == "pending" %>
                    <td><%= link_to 'Edit', edit_leave_application_path(leave_application) %></td>
                    <td><%= link_to 'Destroy', leave_application_path(leave_application), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% end %>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>

        <% if (current_user.is? :director) == false %>
          <table>
            <caption>Leave Applications in Your Department</caption>
            <thead>
              <tr>
                <th>Date</th>
                <th>Name</th>
                <th>Leave Type</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Leave Duration</th>
                <th>Reason</th>
                <th>Status</th>
              </tr>
            </thead>

            <tbody>
              <% @leave_applications.each do |leave_application| %>
                <% if leave_application.user_id != current_user.id %>
                  <tr>
                    <td><%= leave_application.created_at.strftime('%d/%m') %></td>
                    <td><%= leave_application.user.name %></td>
                    <td><%= leave_application.leave_type.name %></td>
                    <td><%= leave_application.start_date.strftime('%d/%m') %></td>
                    <td><%= leave_application.end_date.strftime('%d/%m') %></td>
                    <td><%= leave_application.leave_duration %></td>
                    <td><%= leave_application.reason %></td>
                    <td><%= leave_application.status %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/leave_applications/new.html.erb
<%= render "form" %>

app/views/leave_applications/show.html.erb
<div class="row">
  <div class="large-10 large-centered columns">
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Leave Type</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Leave Duration</th>
          <th>Reason</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @leave_application.created_at.strftime('%d/%m') %></td>
          <td><%= @leave_application.leave_type.name %></td>
          <td><%= @leave_application.start_date.strftime('%d/%m') %></td>
          <td><%= @leave_application.end_date.strftime('%d/%m') %></td>
          <td><%= @leave_application.leave_duration %></td>
          <td><%= @leave_application.reason %></td>
        </tr>
      </tbody>
    </table>

    <a href="/leave_applications" class="button">Back</a>
  </div>
</div>

app/views/leave_types/new.html.erb
<div class="row">
  <div class="large-6 large-offset-3 columns">
    <% if @leave_type.errors.any? %>
      <div class="callout alert" id="error_explanation">
        <h4>
          <%= pluralize(@leave_type.errors.count, "error") %> prohibited this application from being saved:
        </h4>
        <ul>
          <% @leave_type.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= simple_form_for @leave_type do |f| %>
      <%= f.input :name, placeholder: 'e.g. Annual, Sick', error: false %>
      <%= f.button :submit, "Create Leave Type", class: "button" %>
    <% end %>
  </div>
</div>

app/views/leave_types/show.html.erb
<div class="row">
  <div class="large-6 large-offset-3 columns">
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Leave Type</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= @leave_type.id %></td>
          <td><%= @leave_type.name %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/login/index.html.erb
<h1>Saltyleave Login</h1>

<%= simple_form_for :login do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.button :submit, text: 'Login' %>
<% end %>

app/views/users/_form.html.erb
<%= simple_nested_form_for @user do |f| %>
  <%= f.input :name, error: false %>
  <%= f.input :department, collection: User.departments.keys %>
  <%= f.input :region, collection: User.regions.keys, include_blank: false, as: :radio_buttons, error: false %>
  <%= f.input :roles, collection: User.valid_roles, as: :check_boxes %>
  <%= f.input :email, error: false %>
  <%= f.input :password, error: false %>

  <div class="callout">
    <h5>Assign Leave Types</h5>
    <%= f.link_to_add "Add Leave Type", :records %>
    <%= f.simple_fields_for :records do |r| %>
      <div class="large-12 columns">
        <div class="large-5 columns">
          <%= r.input :leave_type_id, label: 'Leave Types', collection: LeaveType.all.collect{|l| [l.name, l.id]}, include_blank: false %>
        </div>
        <div class="large-5 columns">
          <%= r.input :days, as: :integer, placeholder: 14 %>
        </div>
        <br>
        <div class="large-2 columns">
          <%= r.link_to_remove "Remove" %>
        </div>
      </div>
    <% end %>
  </div>

  <%= f.button :submit, "Save User", class: "button" %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="large-6 large-offset-3 columns">
    <% if @user.errors.any? %>
      <div class="callout alert" id="error_explanation">
        <h4>
          <%= pluralize(@user.errors.count, "error") %> prohibited this application from being saved:
        </h4>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render "form" %>

    <br>
    <a href="/users" class="secondary button">Back</a>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="large-10 large-offset-1 columns">
    <table>
      <thead>
        <tr>
          <th><%= sort_link(@q, :id, 'ID') %></th>
          <th><%= sort_link(@q, :name, 'Name') %></th>
          <% if current_user.is_any_of? :director, :admin %>
            <th><%= sort_link(@q, :department, [:department, 'name asc'], 'Department') %></th>
          <% end %>
          <th><%= sort_link(@q, :region, [:region, 'name asc'], 'Region') %></th>
          <th><%= sort_link(@q, :email, 'Email') %></th>
          <% LeaveType.all.collect do |l| %>
            <th><%= sort_link(@q, :records_days, "#{l.name} Leave Days") %></th>
          <% end %>
          <th><%= sort_link(@q, :roles_mask, 'Role(s)') %></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <% if current_user.is_any_of? :director, :admin %>
              <td><%= user.department %></td>
            <% end %>
            <td><%= user.region %></td>
            <td><%= user.email %></td>
            <% if user.records.count > 0 %>
              <% LeaveType.all.each do |l| %>
                <td>
                  <% if user.records.find_by_leave_type_id(l.id)  %>
                    <%= user.records.find_by_leave_type_id(l.id).days %>
                  <% else %>
                    <%= "nil" %>
                  <% end %>
                </td>
              <% end %>
            <% else %>
              <td></td>
              <td></td>
              <td></td>
            <% end %>
            <td><%= user.role_symbols %></td>
            <% if current_user.is? :admin %>
              <td><%= link_to 'Edit', edit_user_path(user.id) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <a href="/users/new" class="button">Add User</a>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="large-6 large-offset-3 columns">
    <% if @user.errors.any? %>
      <div class="callout alert" id="error_explanation">
        <h4>
          <%= pluralize(@user.errors.count, "error") %> prohibited this application from being saved:
        </h4>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="large-10 large-offset-1 columns">
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Department</th>
          <th>Region</th>
          <th>Email</th>
          <% LeaveType.all.collect do |l| %>
            <th><%= "#{l.name} Leave Days" %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @user.id %></td>
          <td><%= @user.name %></td>
          <td><%= @user.department %></td>
          <td><%= @user.region %></td>
          <td><%= @user.email %></td>
          <% LeaveType.all.each do |l| %>
            <td>
              <% if @user.records.find_by_leave_type_id(l.id)  %>
                <%= @user.records.find_by_leave_type_id(l.id).days %>
              <% else %>
                <%= "nil" %>
              <% end %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>

    <a href="/users" class="button">Back</a>
  </div>
</div>